#!/usr/bin/env python3
"""Bootstrap KernelSight indexes and case-study stubs from AutoPiff's corpus_manifest.json."""

import argparse
import json
import os
import sys
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_MANIFEST = REPO_ROOT.parent / "AutoPiff" / "tests" / "validation" / "corpus_manifest.json"

# Map AutoPiff expected_category_primary → human-readable vuln class
CATEGORY_LABEL = {
    "bounds_check": "Buffer Overflow / Bounds Check",
    "lifetime_fix": "Use-After-Free / Lifetime",
    "user_boundary_check": "User Boundary Validation",
    "int_overflow": "Integer Overflow",
    "state_hardening": "State Hardening",
    "race_condition": "Race Condition / TOCTOU",
    "type_confusion": "Type Confusion",
    "authorization": "Authorization / Access Check",
    "info_disclosure": "Information Disclosure",
    "ioctl_hardening": "IOCTL Hardening",
    "mdl_handling": "MDL Handling",
    "object_management": "Object Management",
    "string_handling": "String Handling",
    "pool_hardening": "Pool Hardening",
}

# Map category → KernelSight vuln-class slug
CATEGORY_TO_SLUG = {
    "bounds_check": "buffer-overflow",
    "lifetime_fix": "use-after-free",
    "user_boundary_check": "arbitrary-rw-primitives",
    "int_overflow": "integer-overflow",
    "state_hardening": "logic-bugs",
    "race_condition": "race-conditions",
    "type_confusion": "type-confusion",
    "authorization": "logic-bugs",
    "info_disclosure": "uninitialized-memory",
    "ioctl_hardening": "buffer-overflow",
    "mdl_handling": "arbitrary-rw-primitives",
    "object_management": "use-after-free",
    "string_handling": "buffer-overflow",
    "pool_hardening": "buffer-overflow",
}


def load_manifest(path: Path) -> list[dict]:
    with open(path) as f:
        data = json.load(f)
    return data["cves"]


def generate_cve_index(cves: list[dict]) -> str:
    lines = [
        "# KernelSight CVE Index",
        "# Auto-generated by bootstrap_from_autopiff.py",
        "version: 1",
        "",
        "cves:",
    ]
    for cve in sorted(cves, key=lambda c: c["cve_id"]):
        cat = cve.get("expected_category_primary", "unknown")
        refs = cve.get("references", {})
        rules = []
        for det in cve.get("expected_detections", []):
            rules.extend(det.get("expected_rules", []))

        lines.append(f"  - cve_id: \"{cve['cve_id']}\"")
        lines.append(f"    driver: \"{cve['driver']}\"")
        lines.append(f"    description: \"{cve['description']}\"")
        lines.append(f"    vuln_class: \"{CATEGORY_TO_SLUG.get(cat, 'logic-bugs')}\"")
        lines.append(f"    autopiff_category: \"{cat}\"")
        lines.append(f"    itw: {str(refs.get('itw', False)).lower()}")

        lines.append("    vuln_version:")
        vv = cve["vuln_version"]
        lines.append(f"      build: \"{vv['build']}\"")
        lines.append(f"      kb: \"{vv['kb']}\"")

        lines.append("    fix_version:")
        fv = cve["fix_version"]
        lines.append(f"      build: \"{fv['build']}\"")
        lines.append(f"      kb: \"{fv['kb']}\"")

        lines.append("    references:")
        lines.append(f"      msrc: \"{refs.get('msrc_url', '')}\"")
        lines.append(f"      writeup: \"{refs.get('writeup_url', '')}\"")
        lines.append(f"      poc: \"{refs.get('poc_url', '')}\"")

        lines.append("    autopiff_rules:")
        for rule in rules:
            lines.append(f"      - \"{rule}\"")

        lines.append("    case_study: \"docs/case-studies/{}.md\"".format(cve["cve_id"]))
        lines.append("")

    return "\n".join(lines) + "\n"


def generate_driver_index(cves: list[dict]) -> str:
    drivers = defaultdict(list)
    for cve in cves:
        drivers[cve["driver"]].append(cve["cve_id"])

    lines = [
        "# KernelSight Driver Index",
        "# Auto-generated by bootstrap_from_autopiff.py",
        "version: 1",
        "",
        "drivers:",
    ]
    for driver in sorted(drivers.keys()):
        lines.append(f"  - name: \"{driver}\"")
        lines.append("    cves:")
        for cve_id in sorted(drivers[driver]):
            lines.append(f"      - \"{cve_id}\"")
        lines.append("")

    return "\n".join(lines) + "\n"


def generate_case_study_stub(cve: dict) -> str:
    cat = cve.get("expected_category_primary", "unknown")
    refs = cve.get("references", {})
    rules = []
    funcs = []
    for det in cve.get("expected_detections", []):
        rules.extend(det.get("expected_rules", []))
        if det.get("function_pattern"):
            funcs.extend(det["function_pattern"].split("|"))

    # Filter out generic patterns
    funcs = [f for f in funcs if not f.startswith("FUN_")]

    itw_badge = " :material-alert-circle:{ .itw } **Exploited in the wild**" if refs.get("itw") else ""

    lines = [
        f"# {cve['cve_id']}",
        "",
        f"> {cve['description']}",
        "",
    ]

    if itw_badge:
        lines.append(f"!!! danger \"Exploited in the Wild\"")
        lines.append(f"    This vulnerability was exploited in the wild before or shortly after patching.")
        lines.append("")

    lines.extend([
        "## Summary",
        "",
        "| Field | Value |",
        "|-------|-------|",
        f"| **Driver** | `{cve['driver']}` |",
        f"| **Vulnerability Class** | {CATEGORY_LABEL.get(cat, cat)} |",
        f"| **Vulnerable Build** | `{cve['vuln_version']['build']}` ({cve['vuln_version']['kb']}) |",
        f"| **Fixed Build** | `{cve['fix_version']['build']}` ({cve['fix_version']['kb']}) |",
        f"| **Exploited ITW** | {'Yes' if refs.get('itw') else 'No'} |",
        "",
        "## Affected Functions",
        "",
    ])

    if funcs:
        for func in funcs:
            lines.append(f"- `{func}`")
    else:
        lines.append("*Function names pending analysis.*")

    lines.extend([
        "",
        "## Root Cause",
        "",
        "<!-- TODO: Detailed root cause analysis -->",
        "",
        f"AutoPiff categorizes this as **{cat}** with detection rules:",
        "",
    ])
    for rule in rules:
        lines.append(f"- `{rule}`")

    lines.extend([
        "",
        "## Exploitation",
        "",
        "<!-- TODO: Exploitation details, primitive gained, EoP/RCE path -->",
        "",
        "## Patch Analysis",
        "",
        "<!-- TODO: What changed between vuln and fix builds -->",
        "",
        "## References",
        "",
    ])

    if refs.get("msrc_url"):
        lines.append(f"- [MSRC Advisory]({refs['msrc_url']})")
    if refs.get("writeup_url"):
        lines.append(f"- [Writeup]({refs['writeup_url']})")
    if refs.get("poc_url"):
        lines.append(f"- [PoC]({refs['poc_url']})")

    lines.append("")
    return "\n".join(lines)


def generate_case_studies_index(cves: list[dict]) -> str:
    lines = [
        "# Case Studies",
        "",
        "Real-world Windows kernel CVEs with driver names, affected builds, root causes, and exploitation details.",
        "",
        "## CVE Index",
        "",
        "| CVE | Driver | Class | ITW | Build (Vuln → Fix) |",
        "|-----|--------|-------|-----|---------------------|",
    ]

    for cve in sorted(cves, key=lambda c: c["cve_id"], reverse=True):
        cat = cve.get("expected_category_primary", "unknown")
        refs = cve.get("references", {})
        itw = "Yes" if refs.get("itw") else "No"
        vuln_build = cve["vuln_version"]["build"]
        fix_build = cve["fix_version"]["build"]
        label = CATEGORY_LABEL.get(cat, cat)
        lines.append(
            f"| [{cve['cve_id']}]({cve['cve_id']}.md) "
            f"| `{cve['driver']}` "
            f"| {label} "
            f"| {itw} "
            f"| `{vuln_build}` → `{fix_build}` |"
        )

    lines.extend([
        "",
        "## By Driver",
        "",
    ])

    drivers = defaultdict(list)
    for cve in cves:
        drivers[cve["driver"]].append(cve)

    for driver in sorted(drivers.keys()):
        lines.append(f"### `{driver}`")
        lines.append("")
        for cve in sorted(drivers[driver], key=lambda c: c["cve_id"]):
            lines.append(f"- [{cve['cve_id']}]({cve['cve_id']}.md) — {cve['description']}")
        lines.append("")

    lines.extend([
        "## By Exploitation Status",
        "",
        "### Exploited in the Wild",
        "",
    ])

    for cve in sorted(cves, key=lambda c: c["cve_id"]):
        if cve.get("references", {}).get("itw"):
            lines.append(f"- [{cve['cve_id']}]({cve['cve_id']}.md) — `{cve['driver']}` — {cve['description']}")
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Bootstrap KernelSight from AutoPiff corpus")
    parser.add_argument(
        "--manifest",
        type=Path,
        default=DEFAULT_MANIFEST,
        help="Path to corpus_manifest.json",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing files",
    )
    args = parser.parse_args()

    if not args.manifest.exists():
        print(f"Error: manifest not found at {args.manifest}", file=sys.stderr)
        sys.exit(1)

    cves = load_manifest(args.manifest)
    print(f"Loaded {len(cves)} CVEs from {args.manifest}")

    # Generate YAML indexes
    index_dir = REPO_ROOT / "index"
    index_dir.mkdir(exist_ok=True)

    cve_index_path = index_dir / "cve_index.yaml"
    if args.force or not cve_index_path.exists():
        cve_index_path.write_text(generate_cve_index(cves))
        print(f"  Generated {cve_index_path}")
    else:
        print(f"  Skipped {cve_index_path} (exists, use --force)")

    driver_index_path = index_dir / "driver_index.yaml"
    if args.force or not driver_index_path.exists():
        driver_index_path.write_text(generate_driver_index(cves))
        print(f"  Generated {driver_index_path}")
    else:
        print(f"  Skipped {driver_index_path} (exists, use --force)")

    # Generate case study stubs
    cs_dir = REPO_ROOT / "docs" / "case-studies"
    cs_dir.mkdir(parents=True, exist_ok=True)

    stub_count = 0
    for cve in cves:
        stub_path = cs_dir / f"{cve['cve_id']}.md"
        if args.force or not stub_path.exists():
            stub_path.write_text(generate_case_study_stub(cve))
            stub_count += 1

    print(f"  Generated {stub_count} case study stubs in {cs_dir}")

    # Generate case studies index
    cs_index_path = cs_dir / "index.md"
    if args.force or not cs_index_path.exists():
        cs_index_path.write_text(generate_case_studies_index(cves))
        print(f"  Generated {cs_index_path}")
    else:
        print(f"  Skipped {cs_index_path} (exists, use --force)")

    print(f"\nDone. {len(cves)} CVEs processed.")


if __name__ == "__main__":
    main()
