"""GitHub PR creation manager."""

import logging
import subprocess
from datetime import datetime
from pathlib import Path

from analyzer import ProposedChange

logger = logging.getLogger(__name__)


class PRManager:
    """Creates GitHub PRs with proposed knowledge base changes."""

    def __init__(self, repo_path: Path, config: dict):
        self.repo_path = repo_path
        self.github_config = config.get("github", {})
        self.branch_prefix = self.github_config.get("branch_prefix", "collector")
        self.labels = self.github_config.get("labels", ["collector", "auto-generated"])

    def _run_git(self, *args: str) -> subprocess.CompletedProcess:
        """Run a git command in the repo directory."""
        return subprocess.run(
            ["git", *args],
            cwd=self.repo_path,
            capture_output=True,
            text=True,
            timeout=30,
        )

    def _generate_case_study_stub(self, change: ProposedChange) -> str:
        """Generate a minimal case study markdown stub."""
        adds = change.additions
        cve_id = adds.get("cve_id", "CVE-UNKNOWN")
        drivers = adds.get("drivers", [])
        summary = adds.get("summary", "")
        source_url = change.source_url

        driver_str = f"`{'`, `'.join(drivers)}`" if drivers else "*Unknown*"

        return f"""# {cve_id}

> {summary}

## Summary

| Field | Value |
|-------|-------|
| **Driver** | {driver_str} |
| **Source** | [Link]({source_url}) |

## Affected Functions

*Pending analysis.*

## Root Cause

<!-- TODO: Root cause analysis -->

## References

- [Source]({source_url})
"""

    def _apply_changes(self, changes: list[ProposedChange]) -> list[str]:
        """Apply proposed changes to the repo. Returns list of modified files."""
        modified = []

        for change in changes:
            target = self.repo_path / change.target_file

            if change.change_type == "new_case_study":
                if target.exists():
                    logger.info("Skipping existing file: %s", target)
                    continue
                target.parent.mkdir(parents=True, exist_ok=True)
                content = self._generate_case_study_stub(change)
                target.write_text(content)
                modified.append(change.target_file)

            elif change.change_type == "update_references":
                if not target.exists():
                    logger.warning("Target file not found: %s", target)
                    continue
                # Append reference to the file
                adds = change.additions
                ref_line = f"\n- [{adds['title']}]({adds['url']}) (via {adds['source']})\n"
                content = target.read_text()
                if adds["url"] not in content:
                    content += ref_line
                    target.write_text(content)
                    modified.append(change.target_file)

            elif change.change_type == "new_technique_xref":
                if not target.exists():
                    logger.warning("Target file not found: %s", target)
                    continue
                adds = change.additions
                ref_line = f"\n- [{adds['title']}]({adds['url']})\n"
                content = target.read_text()
                if adds["url"] not in content:
                    content += ref_line
                    target.write_text(content)
                    modified.append(change.target_file)

        return modified

    def _build_pr_body(self, changes: list[ProposedChange]) -> str:
        """Build a structured PR body."""
        lines = ["## Collector Update\n"]

        by_type = {}
        for c in changes:
            by_type.setdefault(c.change_type, []).append(c)

        if "new_case_study" in by_type:
            lines.append("### New Case Studies\n")
            for c in by_type["new_case_study"]:
                lines.append(f"- **{c.additions.get('cve_id', '?')}** — {c.description}")
                lines.append(f"  - Confidence: {c.confidence:.0%}")
                lines.append(f"  - Source: {c.source_url}")
            lines.append("")

        if "update_references" in by_type:
            lines.append("### Updated References\n")
            for c in by_type["update_references"]:
                lines.append(f"- {c.description}")
            lines.append("")

        if "new_technique_xref" in by_type:
            lines.append("### New Technique Cross-References\n")
            for c in by_type["new_technique_xref"]:
                lines.append(f"- {c.description}")
            lines.append("")

        lines.append("---")
        lines.append("*Auto-generated by KernelSight Collector*")
        return "\n".join(lines)

    def create_pr(self, changes: list[ProposedChange], dry_run: bool = False) -> str | None:
        """Create a GitHub PR with the proposed changes.

        Returns the PR URL, or None if dry-run or no changes.
        """
        if not changes:
            logger.info("No changes to propose")
            return None

        # Filter by minimum confidence
        changes = [c for c in changes if c.confidence >= 0.5]
        if not changes:
            logger.info("No changes above confidence threshold")
            return None

        date_str = datetime.utcnow().strftime("%Y%m%d-%H%M")
        # Determine primary source
        sources = set()
        for c in changes:
            url = c.source_url
            if "msrc" in url:
                sources.add("msrc")
            elif "github" in url:
                sources.add("github")
            elif "projectzero" in url or "chromium" in url:
                sources.add("pz")
            else:
                sources.add("blogs")
        source_tag = "-".join(sorted(sources)[:2])
        branch_name = f"{self.branch_prefix}/{date_str}-{source_tag}"

        if dry_run:
            logger.info("DRY RUN — would create branch: %s", branch_name)
            for c in changes:
                logger.info("  [%s] %s (%.0f%%) → %s",
                            c.change_type, c.description, c.confidence * 100, c.target_file)
            return None

        # Create branch
        self._run_git("checkout", "-b", branch_name)

        # Apply changes
        modified = self._apply_changes(changes)
        if not modified:
            logger.info("No files modified after applying changes")
            self._run_git("checkout", "main")
            self._run_git("branch", "-D", branch_name)
            return None

        # Commit
        for f in modified:
            self._run_git("add", f)

        commit_msg = f"collector: add {len(modified)} updates from {source_tag}"
        self._run_git("commit", "-m", commit_msg)

        # Push
        push_result = self._run_git("push", "-u", "origin", branch_name)
        if push_result.returncode != 0:
            logger.error("Push failed: %s", push_result.stderr[:300])
            self._run_git("checkout", "main")
            return None

        # Create PR
        pr_body = self._build_pr_body(changes)
        label_args = []
        for label in self.labels:
            label_args.extend(["--label", label])

        pr_title = f"[Collector] {len(changes)} updates ({date_str})"

        try:
            result = subprocess.run(
                [
                    "gh", "pr", "create",
                    "--title", pr_title,
                    "--body", pr_body,
                    *label_args,
                ],
                cwd=self.repo_path,
                capture_output=True,
                text=True,
                timeout=30,
            )

            if result.returncode == 0:
                pr_url = result.stdout.strip()
                logger.info("Created PR: %s", pr_url)
                return pr_url
            else:
                logger.error("PR creation failed: %s", result.stderr[:300])
                return None

        except Exception:
            logger.exception("PR creation failed")
            return None
        finally:
            self._run_git("checkout", "main")
